name: notewise
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  firebase_core: ^2.15.0
  firebase_analytics: ^10.4.4
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.8.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.12
  cached_network_image: ^3.2.3
  image_picker: ^1.0.1
  firebase_storage: ^11.2.5
  intl: ^0.18.1
  package_info_plus: ^4.0.2
  flutter_launcher_icons: ^0.13.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_1024.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
